#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.backup
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.backup
sed -i '$a8.8.8.8 facebook.com' ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts
